### ISSUE TITLE
menus/listar.phtml

### ISSUE THREAD

**Issue by tungasuca** [argordmel/dbkm#3]
hola, he insertado registros en sistema menus con visibilidad frontend, el tab panel presenta bien las opciones ( Frontend, Dashboard y Sistema) pero no visualiza el tab panel de Sistema al dar click en la pestaña.

**Comment by erm3nda** [comment]
Creo que esto es algo que comenté yo anteriormente sobre la creación de elementos padre y ya ha sido corregido. Actualiza.

**Comment by erm3nda** [comment]
Cerrad el Issue si ya está arreglado, que es el caso.
