### ISSUE TITLE
Problema cargando ficheros js tras pulsar botón Ajax

### ISSUE THREAD

**Issue by erm3nda** [argordmel/dbkm#5]
Hola.

Tengo el menú Backend de DBKM funcioando. He probado a hacer un enlace desde una vista, y el mismo enlace desde el menú. La página de destino es /editor/tiny_mce/ la cual funciona perfectamente cuando pulso un enlace normal.

Parece que la ruta desde la cual se lanza el javascript afecta y mucho a la ruta que necesita el Tag::js para cargar el fichero de TinyMCE, por lo que nunca carga el editor.

Por si no me he explicado bien, resumido es que pulsando un enlace desde Ajax no va y sin Ajax si vá. Tanto desde el menú como desde cualquier otro sitio. He probado todo lo que se me ha ocurrido y no doy con la tecla.

Desactivando Ajax desde ajustes globales funciona desde todos los enlaces.

**Comment by argordmel** [comment]
Hola estimado, segun te entiendo usas un js, pero al cargar con ajax no enlaza los elementos y al cargar normalmente si. 


Si eso es correcto el problema se soluciona usando una función que enlace esos elementos y dicha función la invocas en el kload.js al finalizar el request en el metodo done (allí se vuelven a enlazar otras cosas si miras el código). 


Cualquier cosa pásate por el irc.

**Comment by erm3nda** [comment]
Hoy me he entretenido insertando editores Wysiwyg y cada uno me ha presentado problemas distintos.

Creo que si me has entendido bien, el que no te entiende ahora soy yo. No tengo ni idea de que es kload.js y nunca lo he visto. (cierto es que no he mirado uno a uno los archivos).

Los editore que he insertado son TinyMCE y JQuery-TE. Con ambos me sucede que si cargo los ficheros JS usando la funcion tag::js no funciona via Ajax::link. Si cargo la misma página directamente sin usar el enlace Ajax si funciona.

Otros códigos javascript si son ejecutados en páginas que son llamadas vía Ajax, algunas animaciones de texto y tal. El problem lo dá cuando cargamos ficheros js externos.

Con JQuery-Te he tenido el especial problema de que también tiene un fichero css y un png y claro, al mezclar los tags js y css están en carpetas distintas y al final he optado por no separar los archivos y cargarlas al método tradicional.

Voy a hechar un ojo a ver si localizo lo que me indicas y lo puedo barajar, porque me gusta el Ajax y preferiria no tener que quitarlo.

Gracias.
PD: He entrado al IRC y no hay naidie ahora mismo.

**Comment by erm3nda** [comment]
Siento comentar otra vez este punto, pero este problema persiste y es bastante problemático.
¿Hay alguna forma de automatizar el proceso de editar el kload.js para que cargue?
