### ISSUE TITLE
Sobre el view::content()

### ISSUE THREAD

**Issue by erm3nda** [argordmel/dbkm#6]
He creado un modelo con un método index, quedando en load::model("controlador/index").
Lo cargo directamente con: $this->data = load::model("controlador/index")->index();
En el modelo tengo: class Index {
    function index() {
        $this->data[0] = "This is value no 1";
        $this->data[1] = "This is value no 2";
        echo "Content output from model<br>";
        return $this->data;
    }
}

Si no especifico el nº de item array me hace un array con los items repetidos, este ejemplo hace un output de un array de 4 elementos, el 1 y 2 repetidos:
         $this->data[] = "This is value no 1";
        $this->data[] = "This is value no 2";

El mismo problema sucede si hago un echo desde el modelo, aparece 2 duplicado también.

No estoy seguro de si el problema está en como he llamado al método o en el loader de los modelos que hace una iteración extra.

**Comment by argordmel** [comment]
Me gustaría revisar mejor esa parte,  déjame ver para reunirnos y analizarla
