### ISSUE TITLE
Modelo no encontrado

### ISSUE THREAD

**Issue by gibarel** [argordmel/dbkm#8]
Hola, estoy teniendo problemas para cargar metodos de modelos relacionados con otros modelos con el belongs_to, el error me salta en la vista:
"La excepción se ha generado en el archivo /var/www/html/dbkm-master/default/app/views/seghig/seghigdatos/index.phtml en la línea: 22:"

"22 <td><?php echo $item->getSeghigpersonas()->getGrados()->mne_grado.' '.$item->getSeghigpersonas()->apellido. ', '.$item->getSeghigpersonas()->nombres ?></td> "

y el modelo lo tengo relacionado así:
"protected function initialize() {
        //Relaciones
        $this->belongs_to('seghigpersonas');
        $this->belongs_to('seghigestablecimientos');
        $this->belongs_to('seghigtitulos');
    }"
todos los modelos adentro de models/seghig

En el controlados solo cargo el modelo correspondiente
Load::models('seghig/seghigdatos');

**Comment by argordmel** [comment]
Estimado
Veo que tienes un ->getGrados() eso también es un modelo? está relacionado?
Ese tipo de relaciones es buena para algo simple, pero si usas un foreach es mejor usar los join de mysql.
Saludos
    El Jueves 11 de agosto de 2016 9:04, gibarel <notifications@github.com> escribió:
 

 Hola, estoy teniendo problemas para cargar metodos de modelos relacionados con otros modelos con el belongs_to, el error me salta en la vista:
"La excepción se ha generado en el archivo /var/www/html/dbkm-master/default/app/views/seghig/seghigdatos/index.phtml en la línea: 22:""22 <?php echo $item->getSeghigpersonas()->getGrados()->mne_grado.' '.$item->getSeghigpersonas()->apellido. ', '.$item->getSeghigpersonas()->nombres ?> "y el modelo lo tengo relacionado así:
"protected function initialize() {
 //Relaciones
 $this->belongs_to('seghigpersonas');
 $this->belongs_to('seghigestablecimientos');
 $this->belongs_to('seghigtitulos');
 }"
todos los modelos adentro de models/seghigEn el controlados solo cargo el modelo correspondiente
Load::models('seghig/seghigdatos');—

**Comment by gibarel** [comment]
getGrados() es una relacion que viene del modelo grados y que la relacion de los modelos sería  seghigdatos->seghigpersonas->grados y que funciona en mi aplicacion pero cuando la sumo acá no funciona, la unica diferencia es que yo en mi aplicacion tengo los modelos directamente sobre la carpera models y aca las tengo una carpeta "seghig"

**Comment by gibarel** [comment]
class Seghigdatos extends ActiveRecord {

    protected function initialize() {
        //Relaciones
        $this->belongs_to('seghigpersonas');
....

class Seghigpersonas extends ActiveRecord {

    protected function initialize() {
        //Relaciones
        $this->belongs_to('grados');
....

class Grados extends ActiveRecord {
    
    protected function initialize() {
        //Relaciones
        $this->has_many('seghigpersonas');

**Comment by gibarel** [comment]
class Seghigdatos extends ActiveRecord {

protected function initialize() {
    //Relaciones
    $this->belongs_to('seghigpersonas');
....

class Seghigpersonas extends ActiveRecord {

    //public $debug = true;  //muestra el sql por pantalla
    //public $logger = true; // genera un archivo con las sql,
    
    protected function initialize() {
        //Relaciones
        $this->has_many('seghigdatos');        
        $this->belongs_to('grados');
....

class Grados extends ActiveRecord {

protected function initialize() {
    //Relaciones
    $this->has_many('seghigpersonas');

**Comment by argordmel** [comment]
Intenta cargar todos los modelos desde el controlador debido a que tienes los modelos agrupados por carpeta, kumbiaphp no logra ubicarlo.
Saludos
