### ISSUE TITLE
error js al grabar

### ISSUE THREAD

**Issue by gibarel** [argordmel/dbkm#9]
Hola, me has ayudado otras veces y me surgió un nuevo error. Al crear un registro nuevo en la vista create me da este error:

TypeError: $(...).show(...).spin is not a function
$("#"+target).show().spin('large', 'white');

**Comment by argordmel** [comment]
Hola

Ese error al parecer es porque no se ha cargado la lib de spinner en el template. Mira como está el template: https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L76

También revisa si tienes el id del contenedor del spinner https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L65

Saludos

**Comment by gibarel** [comment]
Muchas gracias Ivan.  Más tarde lo veo y te cuento. 
Saludos.


Gabriel Fiasche15 34 26 49 51

-------- Mensaje original --------
De: "Iván D. Meléndez" <notifications@github.com> 
Fecha: 01/09/2016  13:42  (GMT-03:00) 
A: argordmel/dbkm <dbkm@noreply.github.com> 
CC: gibarel <gibarel@gmail.com>, Author <author@noreply.github.com> 
Asunto: Re: [argordmel/dbkm] error js al grabar (#9) 

Hola

Ese error al parecer es porque no se ha cargado la lib de spinner en el template. Mira como está el template: https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L76

También revisa si tienes el id del contenedor del spinner https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L65

Saludos

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/argordmel/dbkm","title":"argordmel/dbkm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/argordmel/dbkm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@argordmel in #9: Hola\r\n\r\nEse error al parecer es porque no se ha cargado la lib de spinner en el template. Mira como está el template: https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L76\r\n\r\nTambién revisa si tienes el id del contenedor del spinner https://github.com/argordmel/dbkm/blob/master/default/app/views/_shared/templates/backend/default.phtml#L65\r\n\r\nSaludos"}],"action":{"name":"View Issue","url":"https://github.com/argordmel/dbkm/issues/9#issuecomment-244138648"}}}

**Comment by gibarel** [comment]
Listo Ivan, creo que el problema era que estaba cargando otro jquery para usar el autocomplete, comentándolo dejo de dar el error.

...
<?php echo DwForm::close(); ?>
</div>


<?php //echo Tag::js('jquery/jquery-ui-1.11.4/external/jquery/jquery') . PHP_EOL; ?>        
<?php echo Tag::js('jquery/jquery-ui-1.11.4/jquery-ui') . PHP_EOL; ?>        

<script>
    $(document).ready(function () {
        $('input#autocomplete').autocomplete({
